[GLOBAL]
pants_version = "2.11.0"
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.docker"
]

[python]
interpreter_constraints = ["==3.9.*"]
enable_resolves = true
lockfile_generator = "poetry"

[anonymous-telemetry]
enabled = false

[poetry]
version = "poetry==1.1.13"

[source]
root_patterns = [
  '/python'
]
