[tool.poetry]
name = "mre-cartopy"
version = "0.1.0"
description = "MRE of cartopy packaging issue"
authors = []

[tool.poetry.dependencies]
python = "==3.9.*"
Cartopy = "^0.20.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
